format_version: 10
pipelines:
  artifact_build:
    environment_variables:
      DEPLOYMENT: test
      APP_ENV: testing
      # SSH deployment configuration
      DEPLOY_SERVER: your-server-ip
      DEPLOY_USER: deploy
      DEPLOY_PATH: /var/www/laravel
    group: defaultGroup
    environment: build-environment
    resources:
      - build-agent
    materials:
      git_repo:
        git: https://github.com/laravel/laravel.git
        branch: master
    stages:
    - build-stage:
        approval:
          type: manual
          authorization:
            roles:
              - dev
        jobs:
          build:
            tasks:
            - exec:
                command: docker
                arguments:
                  - run
                  - --rm
                  - -v
                  - /var/lib/go-agent/pipelines/build_laravel:/app
                  - -w
                  - /app
                  - php:8.4-fpm
                  - bash
                  - -c
                  - |
                    set -euo pipefail

                    docker-php-source extract
                    cd /usr/src/php/ext/pdo_mysql
                    phpize
                    ./configure
                    make
                    make install

                    cd /usr/local/etc/php/conf.d
                    echo extension=pdo_mysql.so > pdo_mysql.ini
                    cat pdo_mysql.ini

                    apt-get update
                    apt-get install -y git zip

                    cd /app
                    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                    php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
                    php composer-setup.php
                    php -r "unlink('composer-setup.php');"

                    ./composer.phar install --no-dev --optimize-autoloader
           
            - exec:
                command: sudo
                arguments:
                  - chown 
                  - -R 
                  - go:go
                  - /var/lib/go-agent/pipelines
            artifacts:
              - build:
                  source: /var/lib/go-agent/pipelines/build_laravel/vendor
                  destination: vendor
